### Lecture 2 Pandas I

In [101]:
import numpy as np
import pandas as pd
import plotly.express as px

In [102]:
s = pd.Series(["a", "b", "c"]) #创建无索引的Series对象
s

0    a
1    b
2    c
dtype: object

In [103]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [104]:
s.values

array(['a', 'b', 'c'], dtype=object)

In [105]:
s = pd.Series(["a", "b", "c"], index = [10, 100, 1000]) #创建有索引的Series对象
s

10      a
100     b
1000    c
dtype: object

In [106]:
s.index

Index([10, 100, 1000], dtype='int64')

In [107]:
s.values

array(['a', 'b', 'c'], dtype=object)

In [108]:
s.index = [1, 2, 3] #改变索引的值
s

1    a
2    b
3    c
dtype: object

In [109]:
s = pd.Series([4, 0, -2, 6], index = ["a", "b", "c", "d"])
s[["a", "c"]] #索引给定行

a    4
c   -2
dtype: int64

In [110]:
s > 0

a     True
b    False
c    False
d     True
dtype: bool

In [111]:
s[s > 0]

a    4
d    6
dtype: int64

In [112]:
s[s % 2 == 0]

a    4
b    0
c   -2
d    6
dtype: int64

In [113]:
elections = pd.read_csv("../lecture/lec02/data/elections.csv") #读取csv文件为DataFrame
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [114]:
elections = pd.read_csv("../lecture/lec02/data/elections.csv", index_col = "Year")
elections

              Candidate                  Party  Popular vote Result          %
Year
1824     Andrew Jackson  Democratic-Republican        151271   loss  57.210122
1824  John Quincy Adams  Democratic-Republican        113142    win  42.789878
1828     Andrew Jackson             Democratic        642806    win  56.203927
1828  John Quincy Adams    National Republican        500897   loss  43.796073
1832     Andrew Jackson             Democratic        702735    win  54.574789
...                 ...                    ...           ...    ...        ...
2016         Jill Stein                  Green       1457226   loss   1.073699
2020       Joseph Biden             Democratic      81268924    win  51.311515
2020       Donald Trump             Republican      74216154   loss  46.858542
2020       Jo Jorgensen            Libertarian       1865724   loss   1.177979
2020     Howard Hawkins                  Green        405035   loss   0.255731

[182 rows x 5 columns]

In [115]:
elections = elections.reset_index() #重置索引
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [116]:
elections = elections.set_index("Candidate") #设置索引
elections

                   Year                  Party  Popular vote Result          %
Candidate
Andrew Jackson     1824  Democratic-Republican        151271   loss  57.210122
John Quincy Adams  1824  Democratic-Republican        113142    win  42.789878
Andrew Jackson     1828             Democratic        642806    win  56.203927
John Quincy Adams  1828    National Republican        500897   loss  43.796073
Andrew Jackson     1832             Democratic        702735    win  54.574789
...                 ...                    ...           ...    ...        ...
Jill Stein         2016                  Green       1457226   loss   1.073699
Joseph Biden       2020             Democratic      81268924    win  51.311515
Donald Trump       2020             Republican      74216154   loss  46.858542
Jo Jorgensen       2020            Libertarian       1865724   loss   1.177979
Howard Hawkins     2020                  Green        405035   loss   0.255731

[182 rows x 5 columns]

In [117]:
numbers = pd.DataFrame([[1, "one"], [2, "two"]],
                       columns = ["Number", "Eng"])
numbers

   Number  Eng
0       1  one
1       2  two

In [118]:
Fruits = pd.DataFrame({"Fruit" : ["apple", "pear", "banana"],
                       "Price" : [5.99, 6.25, 7]}) #用字典创建DataFrame
Fruits

    Fruit  Price
0   apple   5.99
1    pear   6.25
2  banana   7.00

In [119]:
elections.columns

Index(['Year', 'Party', 'Popular vote', 'Result', '%'], dtype='object')

In [120]:
elections.shape

(182, 5)

In [121]:
elections = elections.reset_index()
elections

,Candidate,Year,Party,Popular vote,Result,%
0,Andrew Jackson,1824,Democratic-Republican,151271,loss,57.210122
1,John Quincy Adams,1824,Democratic-Republican,113142,win,42.789878
2,Andrew Jackson,1828,Democratic,642806,win,56.203927
3,John Quincy Adams,1828,National Republican,500897,loss,43.796073
4,Andrew Jackson,1832,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,Jill Stein,2016,Green,1457226,loss,1.073699
178,Joseph Biden,2020,Democratic,81268924,win,51.311515
179,Donald Trump,2020,Republican,74216154,loss,46.858542
180,Jo Jorgensen,2020,Libertarian,1865724,loss,1.177979
181,Howard Hawkins,2020,Green,405035,loss,0.255731

In [122]:
elections.loc[[3, 5, 7], ["Year", "Party"]] #df.loc[row_lables, column_labels]

   Year                Party
3  1828  National Republican
5  1832  National Republican
7  1836                 Whig

In [123]:
elections.iloc[[3, 5, 7], [1, 2]] #df.iloc[row_integers, column_integers]

   Year                Party
3  1828  National Republican
5  1832  National Republican
7  1836                 Whig

### Lecture 3 Pandas II

In [124]:
#用逻辑运算选择对应的行
logical_operator = (elections["Result"] == "win")

In [125]:
elections[logical_operator]

,Candidate,Year,Party,Popular vote,Result,%
1,John Quincy Adams,1824,Democratic-Republican,113142,win,42.789878
2,Andrew Jackson,1828,Democratic,642806,win,56.203927
4,Andrew Jackson,1832,Democratic,702735,win,54.574789
8,Martin Van Buren,1836,Democratic,763291,win,52.272472
11,William Henry Harrison,1840,Whig,1275583,win,53.051213
13,James Polk,1844,Democratic,1339570,win,50.749477
16,Zachary Taylor,1848,Whig,1360235,win,47.309296
17,Franklin Pierce,1852,Democratic,1605943,win,51.013168
20,James Buchanan,1856,Democratic,1835140,win,45.306080
23,Abraham Lincoln,1860,Republican,1855993,win,39.699408
27,Abraham Lincoln,1864,National Union,2211317,win,54.951512
30,Ulysses Grant,1868,Republican,3013790,win,52.665305
32,Ulysses Grant,1872,Republican,3597439,win,55.928594
33,Rutherford Hayes,1876,Republican,4034142,win,48.471624
36,James Garfield,1880,Republican,4453337,win,48.369234
39,Grover Cleveland,1884,Democratic,4914482,win,48.884933
43,Benjamin Harrison,1888,Republican,5443633,win,47.858041
47,Grover Cleveland,1892,Democratic,5553898,win,46.121393
53,William McKinley,1896,Republican,7112138,win,51.213817
56,William McKinley,1900,Republican,7228864,win,52.342640
60,Theodore Roosevelt,1904,Republican,7630557,win,56.562787
65,William Taft,1908,Republican,7678335,win,52.013300
70,Woodrow Wilson,1912,Democratic,6296284,win,41.933422
74,Woodrow Wilson,1916,Democratic,9126868,win,49.367987
79,Warren Harding,1920,Republican,16144093,win,60.574501
80,Calvin Coolidge,1924,Republican,15723789,win,54.329113
84,Herbert Hoover,1928,Republican,21427123,win,58.368524
86,Franklin Roosevelt,1932,Democratic,22821277,win,57.672125
91,Franklin Roosevelt,1936,Democratic,27752648,win,60.978107
94,Franklin Roosevelt,1940,Democratic,27313945,win,54.871202
97,Franklin Roosevelt,1944,Democratic,25612916,win,53.773801
100,Harry Truman,1948,Democratic,24179347,win,49.601536
106,Dwight Eisenhower,1952,Republican,34075529,win,55.325173
109,Dwight Eisenhower,1956,Republican,35579180,win,57.650654
111,John Kennedy,1960,Democratic,34220984,win,50.082561
114,Lyndon Johnson,1964,Democratic,43127041,win,61.344703
117,Richard Nixon,1968,Republican,31783783,win,43.565246
120,Richard Nixon,1972,Republican,47168710,win,60.907806
123,Jimmy Carter,1976,Democratic,40831881,win,50.271900
131,Ronald Reagan,1980,Republican,43903230,win,50.897944
133,Ronald Reagan,1984,Republican,54455472,win,59.023326
135,George H. W. Bush,1988,Republican,48886597,win,53.518845
140,Bill Clinton,1992,Democratic,44909806,win,43.118485
144,Bill Clinton,1996,Democratic,47400125,win,49.296938
152,George W. Bush,2000,Republican,50456002,win,47.974666
157,George W. Bush,2004,Republican,62040610,win,50.771824
162,Barack Obama,2008,Democratic,69498516,win,53.023510
168,Barack Obama,2012,Democratic,65915795,win,51.258484
173,Donald Trump,2016,Republican,62984828,win,46.407862
178,Joseph Biden,2020,Democratic,81268924,win,51.311515

In [126]:
elections.loc[logical_operator, "Candidate"]

1           John Quincy Adams
2              Andrew Jackson
4              Andrew Jackson
8            Martin Van Buren
11     William Henry Harrison
13                 James Polk
16             Zachary Taylor
17            Franklin Pierce
20             James Buchanan
23            Abraham Lincoln
27            Abraham Lincoln
30              Ulysses Grant
32              Ulysses Grant
33           Rutherford Hayes
36             James Garfield
39           Grover Cleveland
43          Benjamin Harrison
47           Grover Cleveland
53           William McKinley
56           William McKinley
60         Theodore Roosevelt
65               William Taft
70             Woodrow Wilson
74             Woodrow Wilson
79             Warren Harding
80            Calvin Coolidge
84             Herbert Hoover
86         Franklin Roosevelt
91         Franklin Roosevelt
94         Franklin Roosevelt
97         Franklin Roosevelt
100              Harry Truman
106         Dwight Eisenhower
109         Dwight Eisenhower
111              John Kennedy
114            Lyndon Johnson
117             Richard Nixon
120             Richard Nixon
123              Jimmy Carter
131             Ronald Reagan
133             Ronald Reagan
135         George H. W. Bush
140              Bill Clinton
144              Bill Clinton
152            George W. Bush
157            George W. Bush
162              Barack Obama
168              Barack Obama
173              Donald Trump
178              Joseph Biden
Name: Candidate, dtype: object

In [127]:
#用 & 表示 and， | 表示 or， ~ 表示 nagation
elections[(elections["Result"] == "win") & (elections["Year"] < 1900)]

,Candidate,Year,Party,Popular vote,Result,%
1,John Quincy Adams,1824,Democratic-Republican,113142,win,42.789878
2,Andrew Jackson,1828,Democratic,642806,win,56.203927
4,Andrew Jackson,1832,Democratic,702735,win,54.574789
8,Martin Van Buren,1836,Democratic,763291,win,52.272472
11,William Henry Harrison,1840,Whig,1275583,win,53.051213
13,James Polk,1844,Democratic,1339570,win,50.749477
16,Zachary Taylor,1848,Whig,1360235,win,47.309296
17,Franklin Pierce,1852,Democratic,1605943,win,51.013168
20,James Buchanan,1856,Democratic,1835140,win,45.306080
23,Abraham Lincoln,1860,Republican,1855993,win,39.699408
27,Abraham Lincoln,1864,National Union,2211317,win,54.951512
30,Ulysses Grant,1868,Republican,3013790,win,52.665305
32,Ulysses Grant,1872,Republican,3597439,win,55.928594
33,Rutherford Hayes,1876,Republican,4034142,win,48.471624
36,James Garfield,1880,Republican,4453337,win,48.369234
39,Grover Cleveland,1884,Democratic,4914482,win,48.884933
43,Benjamin Harrison,1888,Republican,5443633,win,47.858041
47,Grover Cleveland,1892,Democratic,5553898,win,46.121393
53,William McKinley,1896,Republican,7112138,win,51.213817

In [128]:
elections[elections["Year"].isin([1900, 1904, 1980])]

                  Candidate  Year        Party  Popular vote Result          %
54          John G. Woolley  1900  Prohibition        210864   loss   1.526821
55   William Jennings Bryan  1900   Democratic       6370932   loss  46.130540
56         William McKinley  1900   Republican       7228864    win  52.342640
57          Alton B. Parker  1904   Democratic       5083880   loss  37.685116
58           Eugene V. Debs  1904    Socialist        402810   loss   2.985897
59         Silas C. Swallow  1904  Prohibition        259102   loss   1.920637
60       Theodore Roosevelt  1904   Republican       7630557    win  56.562787
61         Thomas E. Watson  1904     Populist        114070   loss   0.845563
127          Barry Commoner  1980     Citizens        233052   loss   0.270182
128                Ed Clark  1980  Libertarian        921128   loss   1.067883
129            Jimmy Carter  1980   Democratic      35480115   loss  41.132848
130        John B. Anderson  1980  Independent       5719850   loss   6.631143
131           Ronald Reagan  1980   Republican      43903230    win  50.897944

In [129]:
elections[elections["Candidate"].str.startswith("A")]

,Candidate,Year,Party,Popular vote,Result,%
0,Andrew Jackson,1824,Democratic-Republican,151271,loss,57.210122
2,Andrew Jackson,1828,Democratic,642806,win,56.203927
4,Andrew Jackson,1832,Democratic,702735,win,54.574789
23,Abraham Lincoln,1860,Republican,1855993,win,39.699408
27,Abraham Lincoln,1864,National Union,2211317,win,54.951512
42,Alson Streeter,1888,Union Labor,146602,loss,1.288861
57,Alton B. Parker,1904,Democratic,5083880,loss,37.685116
71,Allan L. Benson,1916,Socialist,590524,loss,3.194193
75,Aaron S. Watkins,1920,Prohibition,188787,loss,0.708351
83,Al Smith,1928,Democratic,15015464,loss,40.902853
90,Alf Landon,1936,Republican,16679543,loss,36.648285
105,Adlai Stevenson,1952,Democratic,27375090,loss,44.446312
108,Adlai Stevenson,1956,Democratic,26028028,loss,42.174464
139,Andre Marrou,1992,Libertarian,290087,loss,0.278516
151,Al Gore,2000,Democratic,50999897,loss,48.491813

In [130]:
#通过[]可以直接添加一列 
name_length = elections["Candidate"].str.len()
elections["name_length"] = name_length
elections

,Candidate,Year,Party,Popular vote,Result,%,name_length
0,Andrew Jackson,1824,Democratic-Republican,151271,loss,57.210122,14
1,John Quincy Adams,1824,Democratic-Republican,113142,win,42.789878,17
2,Andrew Jackson,1828,Democratic,642806,win,56.203927,14
3,John Quincy Adams,1828,National Republican,500897,loss,43.796073,17
4,Andrew Jackson,1832,Democratic,702735,win,54.574789,14
...,...,...,...,...,...,...,...
177,Jill Stein,2016,Green,1457226,loss,1.073699,10
178,Joseph Biden,2020,Democratic,81268924,win,51.311515,12
179,Donald Trump,2020,Republican,74216154,loss,46.858542,12
180,Jo Jorgensen,2020,Libertarian,1865724,loss,1.177979,12
181,Howard Hawkins,2020,Green,405035,loss,0.255731,14

In [131]:
#rename 重命名
elections = elections.rename(columns={"name_length":"Length"})
elections

,Candidate,Year,Party,Popular vote,Result,%,Length
0,Andrew Jackson,1824,Democratic-Republican,151271,loss,57.210122,14
1,John Quincy Adams,1824,Democratic-Republican,113142,win,42.789878,17
2,Andrew Jackson,1828,Democratic,642806,win,56.203927,14
3,John Quincy Adams,1828,National Republican,500897,loss,43.796073,17
4,Andrew Jackson,1832,Democratic,702735,win,54.574789,14
...,...,...,...,...,...,...,...
177,Jill Stein,2016,Green,1457226,loss,1.073699,10
178,Joseph Biden,2020,Democratic,81268924,win,51.311515,12
179,Donald Trump,2020,Republican,74216154,loss,46.858542,12
180,Jo Jorgensen,2020,Libertarian,1865724,loss,1.177979,12
181,Howard Hawkins,2020,Green,405035,loss,0.255731,14

In [132]:
#drop 删除 默认删除一行
elections.drop("Length", axis = "columns")

,Candidate,Year,Party,Popular vote,Result,%
0,Andrew Jackson,1824,Democratic-Republican,151271,loss,57.210122
1,John Quincy Adams,1824,Democratic-Republican,113142,win,42.789878
2,Andrew Jackson,1828,Democratic,642806,win,56.203927
3,John Quincy Adams,1828,National Republican,500897,loss,43.796073
4,Andrew Jackson,1832,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,Jill Stein,2016,Green,1457226,loss,1.073699
178,Joseph Biden,2020,Democratic,81268924,win,51.311515
179,Donald Trump,2020,Republican,74216154,loss,46.858542
180,Jo Jorgensen,2020,Libertarian,1865724,loss,1.177979
181,Howard Hawkins,2020,Green,405035,loss,0.255731

In [133]:
elections.describe()

              Year  Popular vote           %      Length
count   182.000000  1.820000e+02  182.000000  182.000000
mean   1934.087912  1.235364e+07   27.470350   14.170330
std      57.048908  1.907715e+07   22.968034    2.927975
min    1824.000000  1.007150e+05    0.098088    7.000000
25%    1889.000000  3.876395e+05    1.219996   12.000000
50%    1936.000000  1.709375e+06   37.677893   14.000000
75%    1988.000000  1.897775e+07   48.354977   16.000000
max    2020.000000  8.126892e+07   61.344703   22.000000

In [134]:
elections["Year"].describe()

count     182.000000
mean     1934.087912
std        57.048908
min      1824.000000
25%      1889.000000
50%      1936.000000
75%      1988.000000
max      2020.000000
Name: Year, dtype: float64

In [135]:
elections["Candidate"].describe()

count               182
unique              132
top       Norman Thomas
freq                  5
Name: Candidate, dtype: object

In [136]:
elections.sample(5)  #抽样

,Candidate,Year,Party,Popular vote,Result,%,Length
172,Darrell Castle,2016,Constitution,203091,loss,0.149640,14
76,Eugene V. Debs,1920,Socialist,913693,loss,3.428282,14
35,James B. Weaver,1880,Greenback,308649,loss,3.352344,15
12,Henry Clay,1844,Whig,1300004,loss,49.250523,10
30,Ulysses Grant,1868,Republican,3013790,win,52.665305,13

In [137]:
elections["Candidate"].value_counts()

Candidate
Norman Thomas             5
Ralph Nader               4
Eugene V. Debs            4
Franklin Roosevelt        4
William Jennings Bryan    3
                         ..
Evan McMullin             1
Hillary Clinton           1
Joseph Biden              1
Jo Jorgensen              1
Howard Hawkins            1
Name: count, Length: 132, dtype: int64

In [138]:
elections["Candidate"].unique()

array(['Andrew Jackson', 'John Quincy Adams', 'Henry Clay',
       'William Wirt', 'Hugh Lawson White', 'Martin Van Buren',
       'William Henry Harrison', 'James Polk', 'Lewis Cass',
       'Zachary Taylor', 'Franklin Pierce', 'John P. Hale',
       'Winfield Scott', 'James Buchanan', 'John C. Frémont',
       'Millard Fillmore', 'Abraham Lincoln', 'John Bell',
       'John C. Breckinridge', 'Stephen A. Douglas',
       'George B. McClellan', 'Horatio Seymour', 'Ulysses Grant',
       'Horace Greeley', 'Rutherford Hayes', 'Samuel J. Tilden',
       'James B. Weaver', 'James Garfield', 'Winfield Scott Hancock',
       'Benjamin Butler', 'Grover Cleveland', 'James G. Blaine',
       'John St. John', 'Alson Streeter', 'Benjamin Harrison',
       'Clinton B. Fisk', 'John Bidwell', 'John M. Palmer',
       'Joshua Levering', 'William Jennings Bryan', 'William McKinley',
       'John G. Woolley', 'Alton B. Parker', 'Eugene V. Debs',
       'Silas C. Swallow', 'Theodore Roosevelt', 'Thomas E. Watson',
       'Eugene W. Chafin', 'William Taft', 'Woodrow Wilson',
       'Allan L. Benson', 'Charles Evans Hughes', 'Frank Hanly',
       'Aaron S. Watkins', 'James M. Cox', 'Parley P. Christensen',
       'Warren Harding', 'Calvin Coolidge', 'John W. Davis',
       'Robert La Follette', 'Al Smith', 'Herbert Hoover',
       'Norman Thomas', 'Franklin Roosevelt', 'William Z. Foster',
       'Alf Landon', 'William Lemke', 'Wendell Willkie',
       'Thomas E. Dewey', 'Claude A. Watson', 'Harry Truman',
       'Henry A. Wallace', 'Strom Thurmond', 'Adlai Stevenson',
       'Dwight Eisenhower', 'Vincent Hallinan', 'T. Coleman Andrews',
       'John Kennedy', 'Richard Nixon', 'Barry Goldwater',
       'Lyndon Johnson', 'George Wallace', 'Hubert Humphrey',
       'George McGovern', 'John G. Schmitz', 'Eugene McCarthy',
       'Gerald Ford', 'Jimmy Carter', 'Lester Maddox', 'Roger MacBride',
       'Thomas J. Anderson', 'Barry Commoner', 'Ed Clark',
       'John B. Anderson', 'Ronald Reagan', 'David Bergland',
       'Walter Mondale', 'George H. W. Bush', 'Lenora Fulani',
       'Michael Dukakis', 'Ron Paul', 'Andre Marrou', 'Bill Clinton',
       'Bo Gritz', 'Ross Perot', 'Bob Dole', 'Harry Browne',
       'Howard Phillips', 'John Hagelin', 'Ralph Nader', 'Al Gore',
       'George W. Bush', 'Pat Buchanan', 'David Cobb', 'John Kerry',
       'Michael Badnarik', 'Michael Peroutka', 'Barack Obama', 'Bob Barr',
       'Chuck Baldwin', 'Cynthia McKinney', 'John McCain', 'Gary Johnson',
       'Jill Stein', 'Mitt Romney', 'Darrell Castle', 'Donald Trump',
       'Evan McMullin', 'Hillary Clinton', 'Joseph Biden', 'Jo Jorgensen',
       'Howard Hawkins'], dtype=object)

In [139]:
elections["%"].sort_values() #排序 默认升序

156     0.098088
141     0.101918
160     0.117542
148     0.118219
165     0.123442
         ...
133    59.023326
79     60.574501
120    60.907806
91     60.978107
114    61.344703
Name: %, Length: 182, dtype: float64

In [140]:
elections.sort_values(by="%", ascending=False)

,Candidate,Year,Party,Popular vote,Result,%,Length
114,Lyndon Johnson,1964,Democratic,43127041,win,61.344703,14
91,Franklin Roosevelt,1936,Democratic,27752648,win,60.978107,18
120,Richard Nixon,1972,Republican,47168710,win,60.907806,13
79,Warren Harding,1920,Republican,16144093,win,60.574501,14
133,Ronald Reagan,1984,Republican,54455472,win,59.023326,13
...,...,...,...,...,...,...,...
165,Cynthia McKinney,2008,Green,161797,loss,0.123442,16
148,John Hagelin,1996,Natural Law,113670,loss,0.118219,12
160,Michael Peroutka,2004,Constitution,143630,loss,0.117542,16
141,Bo Gritz,1992,Populist,106152,loss,0.101918,8
156,David Cobb,2004,Green,119859,loss,0.098088,10

### Lecture 4 Pandas III

In [141]:
#自定义排序 key
elections.sort_values(by="Candidate", key=lambda x : x.str.len(), ascending=False).head()

,Candidate,Year,Party,Popular vote,Result,%,Length
11,William Henry Harrison,1840,Whig,1275583,win,53.051213,22
9,William Henry Harrison,1836,Whig,550816,loss,37.721543,22
52,William Jennings Bryan,1896,Democratic,6509052,loss,46.871053,22
37,Winfield Scott Hancock,1880,Democratic,4444976,loss,48.278422,22
64,William Jennings Bryan,1908,Democratic,6408979,loss,43.414640,22

In [142]:
#用map排序
def dr_ea_count(string):
    return string.count('dr') + string.count('ea')
elections["dr_ea_count"] = elections["Candidate"].map(dr_ea_count)
elections.sort_values(by="dr_ea_count", ascending=False)

,Candidate,Year,Party,Popular vote,Result,%,Length,dr_ea_count
0,Andrew Jackson,1824,Democratic-Republican,151271,loss,57.210122,14,1
2,Andrew Jackson,1828,Democratic,642806,win,56.203927,14,1
4,Andrew Jackson,1832,Democratic,702735,win,54.574789,14,1
35,James B. Weaver,1880,Greenback,308649,loss,3.352344,15,1
48,James B. Weaver,1892,Populist,1041028,loss,8.645038,15,1
...,...,...,...,...,...,...,...,...
177,Jill Stein,2016,Green,1457226,loss,1.073699,10,0
178,Joseph Biden,2020,Democratic,81268924,win,51.311515,12,0
179,Donald Trump,2020,Republican,74216154,loss,46.858542,12,0
180,Jo Jorgensen,2020,Libertarian,1865724,loss,1.177979,12,0
181,Howard Hawkins,2020,Green,405035,loss,0.255731,14,0

In [143]:
#dataframe.gruopby(column_name).agg(aggregation_function)
elections[["Year", "Popular vote"]].groupby("Year").agg(sum)

C:\Users\shuichi\AppData\Local\Temp\ipykernel_15204\524293030.py:2: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  elections[["Year", "Popular vote"]].groupby("Year").agg(sum)

      Popular vote
Year
1824        264413
1828       1143703
1832       1287655
1836       1460216
1840       2404437
1844       2639574
1848       2875196
1852       3148095
1856       4050538
1860       4675115
1864       4024124
1868       5722534
1872       6432200
1876       8322688
1880       9206962
1884      10053163
1888      11374542
1892      12041913
1896      13887147
1900      13810660
1904      13490419
1908      14762253
1912      15014954
1916      18487422
1920      26651632
1924      28941737
1928      36710065
1932      39570723
1936      45512479
1940      49778288
1944      47630845
1948      48747174
1952      61591365
1956      61715137
1960      68329141
1964      70302795
1968      72956740
1972      77442800
1976      81222077
1980      86257375
1984      92260935
1988      91344642
1992     104154416
1996      96152270
2000     105172180
2004     122194959
2008     131071135
2012     128594897
2016     135720167
2020     157755837

In [144]:
elections.groupby("Year").sum(numeric_only=True)

      Popular vote           %  Length  dr_ea_count
Year
1824        264413  100.000000      31            1
1828       1143703  100.000000      31            1
1832       1287655  100.000000      36            1
1836       1460216  100.000000      55            0
1840       2404437  100.000000      38            0
1844       2639574  100.000000      20            0
1848       2875196  100.000000      40            0
1852       3148095  100.000000      41            0
1856       4050538  100.000000      45            0
1860       4675115  100.000000      62            0
1864       4024124  100.000000      34            0
1868       5722534  100.000000      28            0
1872       6432200  100.000000      27            0
1876       8322688  100.000000      32            0
1880       9206962  100.000000      51            1
1884      10053163  100.000000      59            0
1888      11374542  100.000000      62            0
1892      12041913  100.000000      60            1
1896      13887147  100.000000      67            0
1900      13810660  100.000000      53            0
1904      13490419  100.000000      79            0
1908      14762253  100.000000      64            0
1912      15014954  100.000000      74            1
1916      18487422  100.000000      60            1
1920      26651632  100.000000      77            0
1924      28941737  100.000000      46            0
1928      36710065  100.000000      35            0
1932      39570723  100.000000      62            0
1936      45512479  100.000000      54            0
1940      49778288  100.000000      46            0
1944      47630845  100.000000      33            0
1948      48747174  100.000000      86            0
1952      61591365  100.000000      48            0
1956      61715137  100.000000      50            1
1960      68329141  100.000000      25            0
1964      70302795  100.000000      29            0
1968      72956740  100.000000      42            0
1972      77442800  100.000000      43            0
1976      81222077  100.000000      83            0
1980      86257375  100.000000      63            1
1984      92260935  100.000000      41            1
1988      91344642  100.000000      53            0
1992     104154416  100.000000      59            1
1996      96152270  100.000000      80            0
2000     105172180  100.000000      56            0
2004     122194959  100.000000      77            0
2008     131071135  100.000000      71            0
2012     128594897  100.000000      45            0
2016     135720167  100.000000      76            0
2020     157755837   99.603768      50            0

In [145]:
elections.drop("dr_ea_count", axis="columns", inplace=True)
elections.drop("Length", axis="columns", inplace=True)
elections

,Candidate,Year,Party,Popular vote,Result,%
0,Andrew Jackson,1824,Democratic-Republican,151271,loss,57.210122
1,John Quincy Adams,1824,Democratic-Republican,113142,win,42.789878
2,Andrew Jackson,1828,Democratic,642806,win,56.203927
3,John Quincy Adams,1828,National Republican,500897,loss,43.796073
4,Andrew Jackson,1832,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,Jill Stein,2016,Green,1457226,loss,1.073699
178,Joseph Biden,2020,Democratic,81268924,win,51.311515
179,Donald Trump,2020,Republican,74216154,loss,46.858542
180,Jo Jorgensen,2020,Libertarian,1865724,loss,1.177979
181,Howard Hawkins,2020,Green,405035,loss,0.255731

In [146]:
elections.groupby("Year").filter(lambda sf : sf["%"].max() < 45)

,Candidate,Year,Party,Popular vote,Result,%
23,Abraham Lincoln,1860,Republican,1855993,win,39.699408
24,John Bell,1860,Constitutional Union,590901,loss,12.639283
25,John C. Breckinridge,1860,Southern Democratic,848019,loss,18.138998
26,Stephen A. Douglas,1860,Northern Democratic,1380202,loss,29.522311
66,Eugene V. Debs,1912,Socialist,901551,loss,6.004354
67,Eugene W. Chafin,1912,Prohibition,208156,loss,1.386325
68,Theodore Roosevelt,1912,Progressive,4122721,loss,27.457433
69,William Taft,1912,Republican,3486242,loss,23.218466
70,Woodrow Wilson,1912,Democratic,6296284,win,41.933422
115,George Wallace,1968,American Independent,9901118,loss,13.571218
116,Hubert Humphrey,1968,Democratic,31271839,loss,42.863537
117,Richard Nixon,1968,Republican,31783783,win,43.565246
139,Andre Marrou,1992,Libertarian,290087,loss,0.278516
140,Bill Clinton,1992,Democratic,44909806,win,43.118485
141,Bo Gritz,1992,Populist,106152,loss,0.101918
142,George H. W. Bush,1992,Republican,39104550,loss,37.544784
143,Ross Perot,1992,Independent,19743821,loss,18.956298

In [147]:
elections.sort_values(by="%", ascending=False).groupby("Party").first()

,Candidate,Year,Popular vote,Result,%
Party,,,,,
American,Millard Fillmore,1856,873053,loss,21.554001
American Independent,George Wallace,1968,9901118,loss,13.571218
Anti-Masonic,William Wirt,1832,100715,loss,7.821583
Anti-Monopoly,Benjamin Butler,1884,134294,loss,1.335838
Citizens,Barry Commoner,1980,233052,loss,0.270182
Communist,William Z. Foster,1932,103307,loss,0.261069
Constitution,Chuck Baldwin,2008,199750,loss,0.152398
Constitutional Union,John Bell,1860,590901,loss,12.639283
Democratic,Lyndon Johnson,1964,43127041,win,61.344703
Democratic-Republican,Andrew Jackson,1824,151271,loss,57.210122
Dixiecrat,Strom Thurmond,1948,1175930,loss,2.412304
Farmer–Labor,Parley P. Christensen,1920,265398,loss,0.995804
Free Soil,Martin Van Buren,1848,291501,loss,10.138474
Green,Ralph Nader,2000,2882955,loss,2.741176
Greenback,James B. Weaver,1880,308649,loss,3.352344
Independent,Ross Perot,1992,19743821,loss,18.956298
Liberal Republican,Horace Greeley,1872,2834761,loss,44.071406
Libertarian,Gary Johnson,2016,4489235,loss,3.307714
National Democratic,John M. Palmer,1896,134645,loss,0.969566
National Republican,John Quincy Adams,1828,500897,loss,43.796073
National Union,Abraham Lincoln,1864,2211317,win,54.951512
Natural Law,John Hagelin,1996,113670,loss,0.118219
New Alliance,Lenora Fulani,1988,217221,loss,0.237804
Northern Democratic,Stephen A. Douglas,1860,1380202,loss,29.522311
Populist,James B. Weaver,1892,1041028,loss,8.645038
Progressive,Theodore Roosevelt,1912,4122721,loss,27.457433
Prohibition,John Bidwell,1892,270879,loss,2.249468
Reform,Ross Perot,1996,8085294,loss,8.408844
Republican,Richard Nixon,1972,47168710,win,60.907806
Socialist,Eugene V. Debs,1912,901551,loss,6.004354
Southern Democratic,John C. Breckinridge,1860,848019,loss,18.138998
States' Rights,T. Coleman Andrews,1956,107929,loss,0.174883
Taxpayers,Howard Phillips,1996,184656,loss,0.192045
Union,William Lemke,1936,892378,loss,1.960733
Union Labor,Alson Streeter,1888,146602,loss,1.288861
Whig,William Henry Harrison,1840,1275583,win,53.051213

In [148]:
elections.sort_values(by="%").drop_duplicates(["Party"], keep="last")

,Candidate,Year,Party,Popular vote,Result,%
148,John Hagelin,1996,Natural Law,113670,loss,0.118219
164,Chuck Baldwin,2008,Constitution,199750,loss,0.152398
110,T. Coleman Andrews,1956,States' Rights,107929,loss,0.174883
147,Howard Phillips,1996,Taxpayers,184656,loss,0.192045
136,Lenora Fulani,1988,New Alliance,217221,loss,0.237804
89,William Z. Foster,1932,Communist,103307,loss,0.261069
127,Barry Commoner,1980,Citizens,233052,loss,0.270182
50,John M. Palmer,1896,National Democratic,134645,loss,0.969566
78,Parley P. Christensen,1920,Farmer–Labor,265398,loss,0.995804
42,Alson Streeter,1888,Union Labor,146602,loss,1.288861
38,Benjamin Butler,1884,Anti-Monopoly,134294,loss,1.335838
93,William Lemke,1936,Union,892378,loss,1.960733
49,John Bidwell,1892,Prohibition,270879,loss,2.249468
103,Strom Thurmond,1948,Dixiecrat,1175930,loss,2.412304
155,Ralph Nader,2000,Green,2882955,loss,2.741176
175,Gary Johnson,2016,Libertarian,4489235,loss,3.307714
35,James B. Weaver,1880,Greenback,308649,loss,3.352344
66,Eugene V. Debs,1912,Socialist,901551,loss,6.004354
6,William Wirt,1832,Anti-Masonic,100715,loss,7.821583
150,Ross Perot,1996,Reform,8085294,loss,8.408844
48,James B. Weaver,1892,Populist,1041028,loss,8.645038
15,Martin Van Buren,1848,Free Soil,291501,loss,10.138474
24,John Bell,1860,Constitutional Union,590901,loss,12.639283
115,George Wallace,1968,American Independent,9901118,loss,13.571218
25,John C. Breckinridge,1860,Southern Democratic,848019,loss,18.138998
143,Ross Perot,1992,Independent,19743821,loss,18.956298
22,Millard Fillmore,1856,American,873053,loss,21.554001
68,Theodore Roosevelt,1912,Progressive,4122721,loss,27.457433
26,Stephen A. Douglas,1860,Northern Democratic,1380202,loss,29.522311
3,John Quincy Adams,1828,National Republican,500897,loss,43.796073
31,Horace Greeley,1872,Liberal Republican,2834761,loss,44.071406
11,William Henry Harrison,1840,Whig,1275583,win,53.051213
27,Abraham Lincoln,1864,National Union,2211317,win,54.951512
0,Andrew Jackson,1824,Democratic-Republican,151271,loss,57.210122
120,Richard Nixon,1972,Republican,47168710,win,60.907806
114,Lyndon Johnson,1964,Democratic,43127041,win,61.344703

In [149]:
grouped_by_party = elections.groupby("Party")
grouped_by_party.groups

{'American': [22, 126], 'American Independent': [115, 119, 124], 'Anti-Masonic': [6], 'Anti-Monopoly': [38], 'Citizens': [127], 'Communist': [89], 'Constitution': [160, 164, 172], 'Constitutional Union': [24], 'Democratic': [2, 4, 8, 10, 13, 14, 17, 20, 28, 29, 34, 37, 39, 45, 47, 52, 55, 57, 64, 70, 74, 77, 81, 83, 86, 91, 94, 97, 100, 105, 108, 111, 114, 116, 118, 123, 129, 134, 137, 140, 144, 151, 158, 162, 168, 176, 178], 'Democratic-Republican': [0, 1], 'Dixiecrat': [103], 'Farmer–Labor': [78], 'Free Soil': [15, 18], 'Green': [149, 155, 156, 165, 170, 177, 181], 'Greenback': [35], 'Independent': [121, 130, 143, 161, 167, 174], 'Liberal Republican': [31], 'Libertarian': [125, 128, 132, 138, 139, 146, 153, 159, 163, 169, 175, 180], 'National Democratic': [50], 'National Republican': [3, 5], 'National Union': [27], 'Natural Law': [148], 'New Alliance': [136], 'Northern Democratic': [26], 'Populist': [48, 61, 141], 'Progressive': [68, 82, 101, 107], 'Prohibition': [41, 44, 49, 51, 54, 59, 63, 67, 73, 75, 99], 'Reform': [150, 154], 'Republican': [21, 23, 30, 32, 33, 36, 40, 43, 46, 53, 56, 60, 65, 69, 72, 79, 80, 84, 87, 90, 96, 98, 104, 106, 109, 112, 113, 117, 120, 122, 131, 133, 135, 142, 145, 152, 157, 166, 171, 173, 179], 'Socialist': [58, 62, 66, 71, 76, 85, 88, 92, 95, 102], 'Southern Democratic': [25], 'States' Rights': [110], 'Taxpayers': [147], 'Union': [93], 'Union Labor': [42], 'Whig': [7, 9, 11, 12, 16, 19]}

In [150]:
grouped_by_party.get_group("Socialist")

           Candidate  Year      Party  Popular vote Result         %
58    Eugene V. Debs  1904  Socialist        402810   loss  2.985897
62    Eugene V. Debs  1908  Socialist        420852   loss  2.850866
66    Eugene V. Debs  1912  Socialist        901551   loss  6.004354
71   Allan L. Benson  1916  Socialist        590524   loss  3.194193
76    Eugene V. Debs  1920  Socialist        913693   loss  3.428282
85     Norman Thomas  1928  Socialist        267478   loss  0.728623
88     Norman Thomas  1932  Socialist        884885   loss  2.236211
92     Norman Thomas  1936  Socialist        187910   loss  0.412876
95     Norman Thomas  1940  Socialist        116599   loss  0.234237
102    Norman Thomas  1948  Socialist        139569   loss  0.286312

In [151]:
elections_pivot = elections.pivot_table(
    index = "Year",
    columns = "Result",
    values = ["%"],
    aggfunc = np.max,
)
elections_pivot.head(5)

C:\Users\shuichi\AppData\Local\Temp\ipykernel_15204\1091789219.py:1: FutureWarning: The provided callable <function max at 0x000002479329FC10> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  elections_pivot = elections.pivot_table(

                %
Result       loss        win
Year
1824    57.210122  42.789878
1828    43.796073  56.203927
1832    37.603628  54.574789
1836    37.721543  52.272472
1840    46.948787  53.051213

### Lecture 5 Data Wrangling and EDA (Part 1)

In [152]:
tb_df = pd.read_csv("../lecture/lec05/data/cdc_tuberculosis.csv")
tb_df

,Unnamed: 0,No. of TB cases,Unnamed: 2,Unnamed: 3,TB incidence,Unnamed: 5,Unnamed: 6
0,U.S. jurisdiction,2019,2020,2021,2019.00,2020.00,2021.00
1,Total,"8,900","7,173","7,860",2.71,2.16,2.37
2,Alabama,87,72,92,1.77,1.43,1.83
3,Alaska,58,58,58,7.91,7.92,7.92
4,Arizona,183,136,129,2.51,1.89,1.77
5,Arkansas,64,59,69,2.12,1.96,2.28
6,California,"2,111","1,706","1,750",5.35,4.32,4.46
7,Colorado,66,52,58,1.15,0.90,1.00
8,Connecticut,67,54,54,1.88,1.50,1.50
9,Delaware,18,17,43,1.84,1.71,4.29
10,District of Columbia,24,19,19,3.39,2.75,2.84
11,Florida,558,412,499,2.60,1.91,2.29
12,Georgia,302,221,228,2.84,2.06,2.11
13,Hawaii,99,92,106,6.99,6.34,7.35
14,Idaho,7,8,4,0.39,0.43,0.21
15,Illinois,326,216,255,2.57,1.69,2.01
16,Indiana,108,92,127,1.60,1.36,1.87
17,Iowa,52,39,49,1.65,1.22,1.53
18,Kansas,37,37,43,1.27,1.26,1.47
19,Kentucky,66,67,57,1.48,1.49,1.26
20,Louisiana,88,99,86,1.89,2.13,1.86
21,Maine,18,17,14,1.34,1.25,1.02
22,Maryland,209,148,192,3.45,2.40,3.11
23,Massachusetts,178,142,151,2.58,2.02,2.16
24,Michigan,131,101,136,1.31,1.00,1.35
25,Minnesota,148,117,134,2.62,2.05,2.35
26,Mississippi,58,41,45,1.95,1.39,1.53
27,Missouri,70,79,77,1.14,1.28,1.25
28,Montana,2,4,3,0.19,0.37,0.27
29,Nebraska,17,33,22,0.88,1.68,1.12
30,Nevada,53,57,61,1.71,1.83,1.94
31,New Hampshire,6,12,12,0.44,0.87,0.86
32,New Jersey,310,245,279,3.49,2.64,3.01
33,New Mexico,41,29,24,1.95,1.37,1.13
34,New York,746,605,681,3.83,3.00,3.43
35,North Carolina,185,159,178,1.76,1.52,1.69
36,North Dakota,18,10,15,2.36,1.28,1.94
37,Ohio,150,130,149,1.28,1.10,1.26
38,Oklahoma,73,67,69,1.84,1.69,1.73
39,Oregon,70,67,78,1.66,1.58,1.84
40,Pennsylvania,199,156,166,1.55,1.20,1.28
41,Rhode Island,14,7,17,1.32,0.64,1.55
42,South Carolina,80,67,88,1.55,1.31,1.70
43,South Dakota,16,16,12,1.80,1.80,1.34
44,Tennessee,129,113,85,1.89,1.63,1.22
45,Texas,"1,154",883,991,3.98,3.02,3.36
46,Utah,27,29,17,0.84,0.88,0.51
47,Vermont,4,3,2,0.64,0.47,0.31
48,Virginia,191,169,161,2.23,1.96,1.86
49,Washington,221,163,199,2.90,2.11,2.57
50,West Virginia,9,13,7,0.50,0.73,0.39
51,Wisconsin,51,35,66,0.88,0.59,1.12
52,Wyoming,1,0,3,0.17,0.00,0.52

In [153]:
tb_df = pd.read_csv("../lecture/lec05/data/cdc_tuberculosis.csv", header=1) #表头第1行
tb_df

       U.S. jurisdiction   2019   2020   2021  2019.1  2020.1  2021.1
0                  Total  8,900  7,173  7,860    2.71    2.16    2.37
1                Alabama     87     72     92    1.77    1.43    1.83
2                 Alaska     58     58     58    7.91    7.92    7.92
3                Arizona    183    136    129    2.51    1.89    1.77
4               Arkansas     64     59     69    2.12    1.96    2.28
5             California  2,111  1,706  1,750    5.35    4.32    4.46
6               Colorado     66     52     58    1.15    0.90    1.00
7            Connecticut     67     54     54    1.88    1.50    1.50
8               Delaware     18     17     43    1.84    1.71    4.29
9   District of Columbia     24     19     19    3.39    2.75    2.84
10               Florida    558    412    499    2.60    1.91    2.29
11               Georgia    302    221    228    2.84    2.06    2.11
12                Hawaii     99     92    106    6.99    6.34    7.35
13                 Idaho      7      8      4    0.39    0.43    0.21
14              Illinois    326    216    255    2.57    1.69    2.01
15               Indiana    108     92    127    1.60    1.36    1.87
16                  Iowa     52     39     49    1.65    1.22    1.53
17                Kansas     37     37     43    1.27    1.26    1.47
18              Kentucky     66     67     57    1.48    1.49    1.26
19             Louisiana     88     99     86    1.89    2.13    1.86
20                 Maine     18     17     14    1.34    1.25    1.02
21              Maryland    209    148    192    3.45    2.40    3.11
22         Massachusetts    178    142    151    2.58    2.02    2.16
23              Michigan    131    101    136    1.31    1.00    1.35
24             Minnesota    148    117    134    2.62    2.05    2.35
25           Mississippi     58     41     45    1.95    1.39    1.53
26              Missouri     70     79     77    1.14    1.28    1.25
27               Montana      2      4      3    0.19    0.37    0.27
28              Nebraska     17     33     22    0.88    1.68    1.12
29                Nevada     53     57     61    1.71    1.83    1.94
30         New Hampshire      6     12     12    0.44    0.87    0.86
31            New Jersey    310    245    279    3.49    2.64    3.01
32            New Mexico     41     29     24    1.95    1.37    1.13
33              New York    746    605    681    3.83    3.00    3.43
34        North Carolina    185    159    178    1.76    1.52    1.69
35          North Dakota     18     10     15    2.36    1.28    1.94
36                  Ohio    150    130    149    1.28    1.10    1.26
37              Oklahoma     73     67     69    1.84    1.69    1.73
38                Oregon     70     67     78    1.66    1.58    1.84
39          Pennsylvania    199    156    166    1.55    1.20    1.28
40          Rhode Island     14      7     17    1.32    0.64    1.55
41        South Carolina     80     67     88    1.55    1.31    1.70
42          South Dakota     16     16     12    1.80    1.80    1.34
43             Tennessee    129    113     85    1.89    1.63    1.22
44                 Texas  1,154    883    991    3.98    3.02    3.36
45                  Utah     27     29     17    0.84    0.88    0.51
46               Vermont      4      3      2    0.64    0.47    0.31
47              Virginia    191    169    161    2.23    1.96    1.86
48            Washington    221    163    199    2.90    2.11    2.57
49         West Virginia      9     13      7    0.50    0.73    0.39
50             Wisconsin     51     35     66    0.88    0.59    1.12
51               Wyoming      1      0      3    0.17    0.00    0.52

In [154]:
rename_dict = {'2019' : 'TB cases 2019',
               '2020' : 'TB cases 2020',
               '2021' : 'TB cases 2021',
               '2019.1' : 'TB incidence 2019',
               '2020.1' : 'TB incidence 2020',
               '2021.1' : 'TB incidence 2021'}
tb_df = tb_df.rename(columns=rename_dict)
tb_df

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
0,Total,"8,900","7,173","7,860",2.71,2.16,2.37
1,Alabama,87,72,92,1.77,1.43,1.83
2,Alaska,58,58,58,7.91,7.92,7.92
3,Arizona,183,136,129,2.51,1.89,1.77
4,Arkansas,64,59,69,2.12,1.96,2.28
5,California,"2,111","1,706","1,750",5.35,4.32,4.46
6,Colorado,66,52,58,1.15,0.90,1.00
7,Connecticut,67,54,54,1.88,1.50,1.50
8,Delaware,18,17,43,1.84,1.71,4.29
9,District of Columbia,24,19,19,3.39,2.75,2.84
10,Florida,558,412,499,2.60,1.91,2.29
11,Georgia,302,221,228,2.84,2.06,2.11
12,Hawaii,99,92,106,6.99,6.34,7.35
13,Idaho,7,8,4,0.39,0.43,0.21
14,Illinois,326,216,255,2.57,1.69,2.01
15,Indiana,108,92,127,1.60,1.36,1.87
16,Iowa,52,39,49,1.65,1.22,1.53
17,Kansas,37,37,43,1.27,1.26,1.47
18,Kentucky,66,67,57,1.48,1.49,1.26
19,Louisiana,88,99,86,1.89,2.13,1.86
20,Maine,18,17,14,1.34,1.25,1.02
21,Maryland,209,148,192,3.45,2.40,3.11
22,Massachusetts,178,142,151,2.58,2.02,2.16
23,Michigan,131,101,136,1.31,1.00,1.35
24,Minnesota,148,117,134,2.62,2.05,2.35
25,Mississippi,58,41,45,1.95,1.39,1.53
26,Missouri,70,79,77,1.14,1.28,1.25
27,Montana,2,4,3,0.19,0.37,0.27
28,Nebraska,17,33,22,0.88,1.68,1.12
29,Nevada,53,57,61,1.71,1.83,1.94
30,New Hampshire,6,12,12,0.44,0.87,0.86
31,New Jersey,310,245,279,3.49,2.64,3.01
32,New Mexico,41,29,24,1.95,1.37,1.13
33,New York,746,605,681,3.83,3.00,3.43
34,North Carolina,185,159,178,1.76,1.52,1.69
35,North Dakota,18,10,15,2.36,1.28,1.94
36,Ohio,150,130,149,1.28,1.10,1.26
37,Oklahoma,73,67,69,1.84,1.69,1.73
38,Oregon,70,67,78,1.66,1.58,1.84
39,Pennsylvania,199,156,166,1.55,1.20,1.28
40,Rhode Island,14,7,17,1.32,0.64,1.55
41,South Carolina,80,67,88,1.55,1.31,1.70
42,South Dakota,16,16,12,1.80,1.80,1.34
43,Tennessee,129,113,85,1.89,1.63,1.22
44,Texas,"1,154",883,991,3.98,3.02,3.36
45,Utah,27,29,17,0.84,0.88,0.51
46,Vermont,4,3,2,0.64,0.47,0.31
47,Virginia,191,169,161,2.23,1.96,1.86
48,Washington,221,163,199,2.90,2.11,2.57
49,West Virginia,9,13,7,0.50,0.73,0.39
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

In [155]:
tb_df.drop(0)

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
1,Alabama,87,72,92,1.77,1.43,1.83
2,Alaska,58,58,58,7.91,7.92,7.92
3,Arizona,183,136,129,2.51,1.89,1.77
4,Arkansas,64,59,69,2.12,1.96,2.28
5,California,"2,111","1,706","1,750",5.35,4.32,4.46
6,Colorado,66,52,58,1.15,0.90,1.00
7,Connecticut,67,54,54,1.88,1.50,1.50
8,Delaware,18,17,43,1.84,1.71,4.29
9,District of Columbia,24,19,19,3.39,2.75,2.84
10,Florida,558,412,499,2.60,1.91,2.29
11,Georgia,302,221,228,2.84,2.06,2.11
12,Hawaii,99,92,106,6.99,6.34,7.35
13,Idaho,7,8,4,0.39,0.43,0.21
14,Illinois,326,216,255,2.57,1.69,2.01
15,Indiana,108,92,127,1.60,1.36,1.87
16,Iowa,52,39,49,1.65,1.22,1.53
17,Kansas,37,37,43,1.27,1.26,1.47
18,Kentucky,66,67,57,1.48,1.49,1.26
19,Louisiana,88,99,86,1.89,2.13,1.86
20,Maine,18,17,14,1.34,1.25,1.02
21,Maryland,209,148,192,3.45,2.40,3.11
22,Massachusetts,178,142,151,2.58,2.02,2.16
23,Michigan,131,101,136,1.31,1.00,1.35
24,Minnesota,148,117,134,2.62,2.05,2.35
25,Mississippi,58,41,45,1.95,1.39,1.53
26,Missouri,70,79,77,1.14,1.28,1.25
27,Montana,2,4,3,0.19,0.37,0.27
28,Nebraska,17,33,22,0.88,1.68,1.12
29,Nevada,53,57,61,1.71,1.83,1.94
30,New Hampshire,6,12,12,0.44,0.87,0.86
31,New Jersey,310,245,279,3.49,2.64,3.01
32,New Mexico,41,29,24,1.95,1.37,1.13
33,New York,746,605,681,3.83,3.00,3.43
34,North Carolina,185,159,178,1.76,1.52,1.69
35,North Dakota,18,10,15,2.36,1.28,1.94
36,Ohio,150,130,149,1.28,1.10,1.26
37,Oklahoma,73,67,69,1.84,1.69,1.73
38,Oregon,70,67,78,1.66,1.58,1.84
39,Pennsylvania,199,156,166,1.55,1.20,1.28
40,Rhode Island,14,7,17,1.32,0.64,1.55
41,South Carolina,80,67,88,1.55,1.31,1.70
42,South Dakota,16,16,12,1.80,1.80,1.34
43,Tennessee,129,113,85,1.89,1.63,1.22
44,Texas,"1,154",883,991,3.98,3.02,3.36
45,Utah,27,29,17,0.84,0.88,0.51
46,Vermont,4,3,2,0.64,0.47,0.31
47,Virginia,191,169,161,2.23,1.96,1.86
48,Washington,221,163,199,2.90,2.11,2.57
49,West Virginia,9,13,7,0.50,0.73,0.39
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

In [156]:
tb_df.dtypes

U.S. jurisdiction     object
TB cases 2019         object
TB cases 2020         object
TB cases 2021         object
TB incidence 2019    float64
TB incidence 2020    float64
TB incidence 2021    float64
dtype: object

In [157]:
tb_df = (
    pd.read_csv("../lecture/lec05/data/cdc_tuberculosis.csv",
                header=1,
                thousands=',') #1000里有逗号
        .rename(columns=rename_dict)
)

tb_df

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
0,Total,8900,7173,7860,2.71,2.16,2.37
1,Alabama,87,72,92,1.77,1.43,1.83
2,Alaska,58,58,58,7.91,7.92,7.92
3,Arizona,183,136,129,2.51,1.89,1.77
4,Arkansas,64,59,69,2.12,1.96,2.28
5,California,2111,1706,1750,5.35,4.32,4.46
6,Colorado,66,52,58,1.15,0.90,1.00
7,Connecticut,67,54,54,1.88,1.50,1.50
8,Delaware,18,17,43,1.84,1.71,4.29
9,District of Columbia,24,19,19,3.39,2.75,2.84
10,Florida,558,412,499,2.60,1.91,2.29
11,Georgia,302,221,228,2.84,2.06,2.11
12,Hawaii,99,92,106,6.99,6.34,7.35
13,Idaho,7,8,4,0.39,0.43,0.21
14,Illinois,326,216,255,2.57,1.69,2.01
15,Indiana,108,92,127,1.60,1.36,1.87
16,Iowa,52,39,49,1.65,1.22,1.53
17,Kansas,37,37,43,1.27,1.26,1.47
18,Kentucky,66,67,57,1.48,1.49,1.26
19,Louisiana,88,99,86,1.89,2.13,1.86
20,Maine,18,17,14,1.34,1.25,1.02
21,Maryland,209,148,192,3.45,2.40,3.11
22,Massachusetts,178,142,151,2.58,2.02,2.16
23,Michigan,131,101,136,1.31,1.00,1.35
24,Minnesota,148,117,134,2.62,2.05,2.35
25,Mississippi,58,41,45,1.95,1.39,1.53
26,Missouri,70,79,77,1.14,1.28,1.25
27,Montana,2,4,3,0.19,0.37,0.27
28,Nebraska,17,33,22,0.88,1.68,1.12
29,Nevada,53,57,61,1.71,1.83,1.94
30,New Hampshire,6,12,12,0.44,0.87,0.86
31,New Jersey,310,245,279,3.49,2.64,3.01
32,New Mexico,41,29,24,1.95,1.37,1.13
33,New York,746,605,681,3.83,3.00,3.43
34,North Carolina,185,159,178,1.76,1.52,1.69
35,North Dakota,18,10,15,2.36,1.28,1.94
36,Ohio,150,130,149,1.28,1.10,1.26
37,Oklahoma,73,67,69,1.84,1.69,1.73
38,Oregon,70,67,78,1.66,1.58,1.84
39,Pennsylvania,199,156,166,1.55,1.20,1.28
40,Rhode Island,14,7,17,1.32,0.64,1.55
41,South Carolina,80,67,88,1.55,1.31,1.70
42,South Dakota,16,16,12,1.80,1.80,1.34
43,Tennessee,129,113,85,1.89,1.63,1.22
44,Texas,1154,883,991,3.98,3.02,3.36
45,Utah,27,29,17,0.84,0.88,0.51
46,Vermont,4,3,2,0.64,0.47,0.31
47,Virginia,191,169,161,2.23,1.96,1.86
48,Washington,221,163,199,2.90,2.11,2.57
49,West Virginia,9,13,7,0.50,0.73,0.39
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

In [158]:
tb_df.dtypes

U.S. jurisdiction     object
TB cases 2019          int64
TB cases 2020          int64
TB cases 2021          int64
TB incidence 2019    float64
TB incidence 2020    float64
TB incidence 2021    float64
dtype: object

In [159]:
tb_df.drop(0).sum()

U.S. jurisdiction    AlabamaAlaskaArizonaArkansasCaliforniaColorado...
TB cases 2019                                                     8900
TB cases 2020                                                     7173
TB cases 2021                                                     7860
TB incidence 2019                                               107.23
TB incidence 2020                                                90.93
TB incidence 2021                                               100.57
dtype: object

In [160]:
census_2010s_df = pd.read_csv("../lecture/lec05/data/nst-est2019-01.csv",
                              header=3,
                              thousands=',')
census_2010s_df = (
    census_2010s_df
    .rename(columns={"Unnamed: 0": "Geographic Area"})
    .drop(columns={"Census", "Estimates Base"})
    .convert_dtypes()
    .dropna()
)
census_2010s_df

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
1,Northeast,55380134,55604223,55775216,55901806,56006011,56034684,56042330,56059240,56046620,55982803
2,Midwest,66974416,67157800,67336743,67560379,67745167,67860583,67987540,68126781,68236628,68329004
3,South,114866680,116006522,117241208,118364400,119624037,120997341,122351760,123542189,124569433,125580448
4,West,72100436,72788329,73477823,74167130,74925793,75742555,76559681,77257329,77834820,78347268
5,.Alabama,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
6,.Alaska,713910,722128,730443,737068,736283,737498,741456,739700,735139,731545
7,.Arizona,6407172,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717
8,.Arkansas,2921964,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804
9,.California,37319502,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223
10,.Colorado,5047349,5121108,5192647,5269035,5350101,5450623,5539215,5611885,5691287,5758736
11,.Connecticut,3579114,3588283,3594547,3594841,3594524,3587122,3578141,3573297,3571520,3565287
12,.Delaware,899593,907381,915179,923576,932487,941252,948921,956823,965479,973764
13,.District of Columbia,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
14,.Florida,18845537,19053237,19297822,19545621,19845911,20209042,20613477,20963613,21244317,21477737
15,.Georgia,9711881,9802431,9901430,9972479,10067278,10178447,10301890,10410330,10511131,10617423
16,.Hawaii,1363963,1379329,1394804,1408243,1414538,1422052,1427559,1424393,1420593,1415872
17,.Idaho,1570746,1583910,1595324,1611206,1631112,1651059,1682380,1717715,1750536,1787065
18,.Illinois,12840503,12867454,12882510,12895129,12884493,12858913,12820527,12778828,12723071,12671821
19,.Indiana,6490432,6516528,6537703,6568713,6593644,6608422,6634304,6658078,6695497,6732219
20,.Iowa,3050745,3066336,3076190,3092997,3109350,3120960,3131371,3141550,3148618,3155070
21,.Kansas,2858190,2869225,2885257,2893212,2900475,2909011,2910844,2908718,2911359,2913314
22,.Kentucky,4348181,4369821,4386346,4404659,4414349,4425976,4438182,4452268,4461153,4467673
23,.Louisiana,4544532,4575625,4600972,4624527,4644013,4664628,4678135,4670560,4659690,4648794
24,.Maine,1327629,1328284,1327729,1328009,1330513,1328262,1331317,1334612,1339057,1344212
25,.Maryland,5788645,5839419,5886992,5923188,5957283,5985562,6003323,6023868,6035802,6045680
26,.Massachusetts,6566307,6613583,6663005,6713315,6762596,6794228,6823608,6859789,6882635,6892503
27,.Michigan,9877510,9882412,9897145,9913065,9929848,9931715,9950571,9973114,9984072,9986857
28,.Minnesota,5310828,5346143,5376643,5413479,5451079,5482032,5522744,5566230,5606249,5639632
29,.Mississippi,2970548,2978731,2983816,2988711,2990468,2988471,2987938,2988510,2981020,2976149
30,.Missouri,5995974,6010275,6024367,6040715,6056202,6071732,6087135,6106670,6121623,6137428
31,.Montana,990697,997316,1003783,1013569,1021869,1030475,1040859,1052482,1060665,1068778
32,.Nebraska,1829542,1840672,1853303,1865279,1879321,1891277,1905616,1915947,1925614,1934408
33,.Nevada,2702405,2712730,2743996,2775970,2817628,2866939,2917563,2969905,3027341,3080156
34,.New Hampshire,1316762,1320202,1324232,1326622,1333341,1336350,1342307,1348787,1353465,1359711
35,.New Jersey,8799446,8828117,8844942,8856972,8864525,8867949,8870827,8885525,8886025,8882190
36,.New Mexico,2064552,2080450,2087309,2092273,2089568,2089291,2091630,2091784,2092741,2096829
37,.New York,19399878,19499241,19572932,19624447,19651049,19654666,19633428,19589572,19530351,19453561
38,.North Carolina,9574323,9657592,9749476,9843336,9932887,10031646,10154788,10268233,10381615,10488084
39,.North Dakota,674715,685225,701176,722036,737401,754066,754434,754942,758080,762062
40,.Ohio,11539336,11544663,11548923,11576684,11602700,11617527,11634370,11659650,11676341,11689100
41,.Oklahoma,3759944,3788379,3818814,3853214,3878187,3909500,3926331,3931316,3940235,3956971
42,.Oregon,3837491,3872036,3899001,3922468,3963244,4015792,4089976,4143625,4181886,4217737
43,.Pennsylvania,12711160,12745815,12767118,12776309,12788313,12784826,12782275,12787641,12800922,12801989
44,.Rhode Island,1053959,1053649,1054621,1055081,1055936,1056065,1056770,1055673,1058287,1059361
45,.South Carolina,4635649,4671994,4717354,4764080,4823617,4891938,4957968,5021268,5084156,5148714
46,.South Dakota,816166,823579,833566,842316,849129,853988,862996,872868,878698,884659
47,.Tennessee,6355311,6399291,6453898,6494340,6541223,6591170,6646010,6708799,6771631,6829174
48,.Texas,25241971,25645629,26084481,26480266,26964333,27470056,27914410,28295273,28628666,28995881
49,.Utah,2775332,2814384,2853375,2897640,2936879,2981835,3041868,3101042,3153550,3205958
50,.Vermont,625879,627049,626090,626210,625214,625216,623657,624344,624358,623989
51,.Virginia,8023699,8101155,8185080,8252427,8310993,8361808,8410106,8463587,8501286,8535519
52,.Washington,6742830,6826627,6897058,6963985,7054655,7163657,7294771,7423362,7523869,7614893
53,.West Virginia,1854239,1856301,1856872,1853914,1849489,1842050,1831023,1817004,1804291,1792147
54,.Wisconsin,5690475,5705288,5719960,5736754,5751525,5760940,5772628,5790186,5807406,5822434
55,.Wyoming,564487,567299,576305,582122,582531,585613,584215,578931,577601,578759
57,Puerto Rico,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325286,3193354,3193694

In [161]:
census_2010s_df['Geographic Area'] = census_2010s_df['Geographic Area'].str.strip('.')
census_2010s_df

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
1,Northeast,55380134,55604223,55775216,55901806,56006011,56034684,56042330,56059240,56046620,55982803
2,Midwest,66974416,67157800,67336743,67560379,67745167,67860583,67987540,68126781,68236628,68329004
3,South,114866680,116006522,117241208,118364400,119624037,120997341,122351760,123542189,124569433,125580448
4,West,72100436,72788329,73477823,74167130,74925793,75742555,76559681,77257329,77834820,78347268
5,Alabama,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
6,Alaska,713910,722128,730443,737068,736283,737498,741456,739700,735139,731545
7,Arizona,6407172,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717
8,Arkansas,2921964,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804
9,California,37319502,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223
10,Colorado,5047349,5121108,5192647,5269035,5350101,5450623,5539215,5611885,5691287,5758736
11,Connecticut,3579114,3588283,3594547,3594841,3594524,3587122,3578141,3573297,3571520,3565287
12,Delaware,899593,907381,915179,923576,932487,941252,948921,956823,965479,973764
13,District of Columbia,605226,619800,634924,650581,662328,675400,685815,694906,701547,705749
14,Florida,18845537,19053237,19297822,19545621,19845911,20209042,20613477,20963613,21244317,21477737
15,Georgia,9711881,9802431,9901430,9972479,10067278,10178447,10301890,10410330,10511131,10617423
16,Hawaii,1363963,1379329,1394804,1408243,1414538,1422052,1427559,1424393,1420593,1415872
17,Idaho,1570746,1583910,1595324,1611206,1631112,1651059,1682380,1717715,1750536,1787065
18,Illinois,12840503,12867454,12882510,12895129,12884493,12858913,12820527,12778828,12723071,12671821
19,Indiana,6490432,6516528,6537703,6568713,6593644,6608422,6634304,6658078,6695497,6732219
20,Iowa,3050745,3066336,3076190,3092997,3109350,3120960,3131371,3141550,3148618,3155070
21,Kansas,2858190,2869225,2885257,2893212,2900475,2909011,2910844,2908718,2911359,2913314
22,Kentucky,4348181,4369821,4386346,4404659,4414349,4425976,4438182,4452268,4461153,4467673
23,Louisiana,4544532,4575625,4600972,4624527,4644013,4664628,4678135,4670560,4659690,4648794
24,Maine,1327629,1328284,1327729,1328009,1330513,1328262,1331317,1334612,1339057,1344212
25,Maryland,5788645,5839419,5886992,5923188,5957283,5985562,6003323,6023868,6035802,6045680
26,Massachusetts,6566307,6613583,6663005,6713315,6762596,6794228,6823608,6859789,6882635,6892503
27,Michigan,9877510,9882412,9897145,9913065,9929848,9931715,9950571,9973114,9984072,9986857
28,Minnesota,5310828,5346143,5376643,5413479,5451079,5482032,5522744,5566230,5606249,5639632
29,Mississippi,2970548,2978731,2983816,2988711,2990468,2988471,2987938,2988510,2981020,2976149
30,Missouri,5995974,6010275,6024367,6040715,6056202,6071732,6087135,6106670,6121623,6137428
31,Montana,990697,997316,1003783,1013569,1021869,1030475,1040859,1052482,1060665,1068778
32,Nebraska,1829542,1840672,1853303,1865279,1879321,1891277,1905616,1915947,1925614,1934408
33,Nevada,2702405,2712730,2743996,2775970,2817628,2866939,2917563,2969905,3027341,3080156
34,New Hampshire,1316762,1320202,1324232,1326622,1333341,1336350,1342307,1348787,1353465,1359711
35,New Jersey,8799446,8828117,8844942,8856972,8864525,8867949,8870827,8885525,8886025,8882190
36,New Mexico,2064552,2080450,2087309,2092273,2089568,2089291,2091630,2091784,2092741,2096829
37,New York,19399878,19499241,19572932,19624447,19651049,19654666,19633428,19589572,19530351,19453561
38,North Carolina,9574323,9657592,9749476,9843336,9932887,10031646,10154788,10268233,10381615,10488084
39,North Dakota,674715,685225,701176,722036,737401,754066,754434,754942,758080,762062
40,Ohio,11539336,11544663,11548923,11576684,11602700,11617527,11634370,11659650,11676341,11689100
41,Oklahoma,3759944,3788379,3818814,3853214,3878187,3909500,3926331,3931316,3940235,3956971
42,Oregon,3837491,3872036,3899001,3922468,3963244,4015792,4089976,4143625,4181886,4217737
43,Pennsylvania,12711160,12745815,12767118,12776309,12788313,12784826,12782275,12787641,12800922,12801989
44,Rhode Island,1053959,1053649,1054621,1055081,1055936,1056065,1056770,1055673,1058287,1059361
45,South Carolina,4635649,4671994,4717354,4764080,4823617,4891938,4957968,5021268,5084156,5148714
46,South Dakota,816166,823579,833566,842316,849129,853988,862996,872868,878698,884659
47,Tennessee,6355311,6399291,6453898,6494340,6541223,6591170,6646010,6708799,6771631,6829174
48,Texas,25241971,25645629,26084481,26480266,26964333,27470056,27914410,28295273,28628666,28995881
49,Utah,2775332,2814384,2853375,2897640,2936879,2981835,3041868,3101042,3153550,3205958
50,Vermont,625879,627049,626090,626210,625214,625216,623657,624344,624358,623989
51,Virginia,8023699,8101155,8185080,8252427,8310993,8361808,8410106,8463587,8501286,8535519
52,Washington,6742830,6826627,6897058,6963985,7054655,7163657,7294771,7423362,7523869,7614893
53,West Virginia,1854239,1856301,1856872,1853914,1849489,1842050,1831023,1817004,1804291,1792147
54,Wisconsin,5690475,5705288,5719960,5736754,5751525,5760940,5772628,5790186,5807406,5822434
55,Wyoming,564487,567299,576305,582122,582531,585613,584215,578931,577601,578759
57,Puerto Rico,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325286,3193354,3193694

In [162]:
census_2020s_df = pd.read_csv("../lecture/lec05/data/NST-EST2022-POP.csv",
                              header=3,
                              thousands=',')
census_2020s_df = (
    census_2020s_df
    .drop(columns=["Unnamed: 1"])
    .rename(columns={"Unnamed: 0" : "Geographic Area"})
    .convert_dtypes()
    .dropna()
)
census_2020s_df['Geographic Area'] = census_2020s_df['Geographic Area'].str.strip('.')
census_2020s_df

         Geographic Area       2020       2021       2022
0          United States  331511512  332031554  333287557
1              Northeast   57448898   57259257   57040406
2                Midwest   68961043   68836505   68787595
3                  South  126450613  127346029  128716192
4                   West   78650958   78589763   78743364
5                Alabama    5031362    5049846    5074296
6                 Alaska     732923     734182     733583
7                Arizona    7179943    7264877    7359197
8               Arkansas    3014195    3028122    3045637
9             California   39501653   39142991   39029342
10              Colorado    5784865    5811297    5839926
11           Connecticut    3597362    3623355    3626205
12              Delaware     992114    1004807    1018396
13  District of Columbia     670868     668791     671803
14               Florida   21589602   21828069   22244823
15               Georgia   10729828   10788029   10912876
16                Hawaii    1451043    1447154    1440196
17                 Idaho    1849202    1904314    1939033
18              Illinois   12786580   12686469   12582032
19               Indiana    6788799    6813532    6833037
20                  Iowa    3190571    3197689    3200517
21                Kansas    2937919    2937922    2937150
22              Kentucky    4507445    4506589    4512310
23             Louisiana    4651664    4627098    4590241
24                 Maine    1363557    1377238    1385340
25              Maryland    6173205    6174610    6164660
26         Massachusetts    6995729    6989690    6981974
27              Michigan   10069577   10037504   10034113
28             Minnesota    5709852    5711471    5717184
29           Mississippi    2958141    2949586    2940057
30              Missouri    6153998    6169823    6177957
31               Montana    1087075    1106227    1122867
32              Nebraska    1962642    1963554    1967923
33                Nevada    3115648    3146402    3177772
34         New Hampshire    1378587    1387505    1395231
35            New Jersey    9271689    9267961    9261699
36            New Mexico    2118390    2116677    2113344
37              New York   20108296   19857492   19677151
38        North Carolina   10449445   10565885   10698973
39          North Dakota     779518     777934     779261
40                  Ohio   11797517   11764342   11756058
41              Oklahoma    3964912    3991225    4019800
42                Oregon    4244795    4256301    4240137
43          Pennsylvania   12994440   13012059   12972008
44          Rhode Island    1096345    1096985    1093734
45        South Carolina    5131848    5193266    5282634
46          South Dakota     887799     896164     909824
47             Tennessee    6925619    6968351    7051339
48                 Texas   29232474   29558864   30029572
49                  Utah    3283785    3339113    3380800
50               Vermont     642893     646972     647064
51              Virginia    8636471    8657365    8683619
52            Washington    7724031    7740745    7785786
53         West Virginia    1791420    1785526    1775156
54             Wisconsin    5896271    5880101    5892539
55               Wyoming     577605     579483     581381
57           Puerto Rico    3281557    3262693    3221789

In [163]:
#show the three tables
display(tb_df.tail(2))
display(census_2010s_df.tail(2))
display(census_2020s_df.tail(2))

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

,Geographic Area,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
55,Wyoming,564487,567299,576305,582122,582531,585613,584215,578931,577601,578759
57,Puerto Rico,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325286,3193354,3193694

   Geographic Area     2020     2021     2022
55         Wyoming   577605   579483   581381
57     Puerto Rico  3281557  3262693  3221789

In [164]:
#pd.merge join data on keys
tb_census_df = (
    tb_df
    .merge(right=census_2010s_df[["Geographic Area", "2019"]],
           left_on="U.S. jurisdiction", right_on="Geographic Area")
    .drop(columns="Geographic Area")
    .merge(right=census_2020s_df[["Geographic Area", "2020", "2021"]],
           left_on="U.S. jurisdiction", right_on="Geographic Area")
    .drop(columns="Geographic Area")
)
tb_census_df.tail()

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,2019,2020,2021
46,Virginia,191,169,161,2.23,1.96,1.86,8535519,8636471,8657365
47,Washington,221,163,199,2.90,2.11,2.57,7614893,7724031,7740745
48,West Virginia,9,13,7,0.50,0.73,0.39,1792147,1791420,1785526
49,Wisconsin,51,35,66,0.88,0.59,1.12,5822434,5896271,5880101
50,Wyoming,1,0,3,0.17,0.00,0.52,578759,577605,579483

In [165]:
tb_census_df["recompute incidence 2019"] = (
    tb_census_df["TB cases 2019"]/tb_census_df["2019"] * 100000
)
tb_census_df

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,2019,2020,2021,recompute incidence 2019
0,Alabama,87,72,92,1.77,1.43,1.83,4903185,5031362,5049846,1.774357
1,Alaska,58,58,58,7.91,7.92,7.92,731545,732923,734182,7.928425
2,Arizona,183,136,129,2.51,1.89,1.77,7278717,7179943,7264877,2.514179
3,Arkansas,64,59,69,2.12,1.96,2.28,3017804,3014195,3028122,2.120747
4,California,2111,1706,1750,5.35,4.32,4.46,39512223,39501653,39142991,5.342651
5,Colorado,66,52,58,1.15,0.90,1.00,5758736,5784865,5811297,1.146085
6,Connecticut,67,54,54,1.88,1.50,1.50,3565287,3597362,3623355,1.879232
7,Delaware,18,17,43,1.84,1.71,4.29,973764,992114,1004807,1.848497
8,District of Columbia,24,19,19,3.39,2.75,2.84,705749,670868,668791,3.400642
9,Florida,558,412,499,2.60,1.91,2.29,21477737,21589602,21828069,2.598039
10,Georgia,302,221,228,2.84,2.06,2.11,10617423,10729828,10788029,2.844381
11,Hawaii,99,92,106,6.99,6.34,7.35,1415872,1451043,1447154,6.992157
12,Idaho,7,8,4,0.39,0.43,0.21,1787065,1849202,1904314,0.391704
13,Illinois,326,216,255,2.57,1.69,2.01,12671821,12786580,12686469,2.572637
14,Indiana,108,92,127,1.60,1.36,1.87,6732219,6788799,6813532,1.604226
15,Iowa,52,39,49,1.65,1.22,1.53,3155070,3190571,3197689,1.648141
16,Kansas,37,37,43,1.27,1.26,1.47,2913314,2937919,2937922,1.270031
17,Kentucky,66,67,57,1.48,1.49,1.26,4467673,4507445,4506589,1.477279
18,Louisiana,88,99,86,1.89,2.13,1.86,4648794,4651664,4627098,1.892964
19,Maine,18,17,14,1.34,1.25,1.02,1344212,1363557,1377238,1.339074
20,Maryland,209,148,192,3.45,2.40,3.11,6045680,6173205,6174610,3.457014
21,Massachusetts,178,142,151,2.58,2.02,2.16,6892503,6995729,6989690,2.582516
22,Michigan,131,101,136,1.31,1.00,1.35,9986857,10069577,10037504,1.311724
23,Minnesota,148,117,134,2.62,2.05,2.35,5639632,5709852,5711471,2.624285
24,Mississippi,58,41,45,1.95,1.39,1.53,2976149,2958141,2949586,1.948827
25,Missouri,70,79,77,1.14,1.28,1.25,6137428,6153998,6169823,1.140543
26,Montana,2,4,3,0.19,0.37,0.27,1068778,1087075,1106227,0.18713
27,Nebraska,17,33,22,0.88,1.68,1.12,1934408,1962642,1963554,0.878822
28,Nevada,53,57,61,1.71,1.83,1.94,3080156,3115648,3146402,1.720692
29,New Hampshire,6,12,12,0.44,0.87,0.86,1359711,1378587,1387505,0.44127
30,New Jersey,310,245,279,3.49,2.64,3.01,8882190,9271689,9267961,3.49013
31,New Mexico,41,29,24,1.95,1.37,1.13,2096829,2118390,2116677,1.955334
32,New York,746,605,681,3.83,3.00,3.43,19453561,20108296,19857492,3.834773
33,North Carolina,185,159,178,1.76,1.52,1.69,10488084,10449445,10565885,1.763907
34,North Dakota,18,10,15,2.36,1.28,1.94,762062,779518,777934,2.362013
35,Ohio,150,130,149,1.28,1.10,1.26,11689100,11797517,11764342,1.283247
36,Oklahoma,73,67,69,1.84,1.69,1.73,3956971,3964912,3991225,1.844845
37,Oregon,70,67,78,1.66,1.58,1.84,4217737,4244795,4256301,1.659658
38,Pennsylvania,199,156,166,1.55,1.20,1.28,12801989,12994440,13012059,1.554446
39,Rhode Island,14,7,17,1.32,0.64,1.55,1059361,1096345,1096985,1.321551
40,South Carolina,80,67,88,1.55,1.31,1.70,5148714,5131848,5193266,1.553786
41,South Dakota,16,16,12,1.80,1.80,1.34,884659,887799,896164,1.808606
42,Tennessee,129,113,85,1.89,1.63,1.22,6829174,6925619,6968351,1.888955
43,Texas,1154,883,991,3.98,3.02,3.36,28995881,29232474,29558864,3.979876
44,Utah,27,29,17,0.84,0.88,0.51,3205958,3283785,3339113,0.842182
45,Vermont,4,3,2,0.64,0.47,0.31,623989,642893,646972,0.641037
46,Virginia,191,169,161,2.23,1.96,1.86,8535519,8636471,8657365,2.237708
47,Washington,221,163,199,2.90,2.11,2.57,7614893,7724031,7740745,2.902208
48,West Virginia,9,13,7,0.50,0.73,0.39,1792147,1791420,1785526,0.502191
49,Wisconsin,51,35,66,0.88,0.59,1.12,5822434,5896271,5880101,0.875922
50,Wyoming,1,0,3,0.17,0.00,0.52,578759,577605,579483,0.172783

In [166]:
for year in [2019, 2020, 2021]:
    tb_census_df[f"recompute incidence {year}"] = (
        tb_census_df[f"TB cases {year}"]/tb_census_df[f"{year}"]*100000
    )
tb_census_df

,U.S. jurisdiction,TB cases 2019,TB cases 2020,TB cases 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,2019,2020,2021,recompute incidence 2019,recompute incidence 2020,recompute incidence 2021
0,Alabama,87,72,92,1.77,1.43,1.83,4903185,5031362,5049846,1.774357,1.431024,1.821838
1,Alaska,58,58,58,7.91,7.92,7.92,731545,732923,734182,7.928425,7.913519,7.899949
2,Arizona,183,136,129,2.51,1.89,1.77,7278717,7179943,7264877,2.514179,1.894165,1.775667
3,Arkansas,64,59,69,2.12,1.96,2.28,3017804,3014195,3028122,2.120747,1.957405,2.27864
4,California,2111,1706,1750,5.35,4.32,4.46,39512223,39501653,39142991,5.342651,4.318807,4.470788
5,Colorado,66,52,58,1.15,0.90,1.00,5758736,5784865,5811297,1.146085,0.898897,0.998056
6,Connecticut,67,54,54,1.88,1.50,1.50,3565287,3597362,3623355,1.879232,1.5011,1.490331
7,Delaware,18,17,43,1.84,1.71,4.29,973764,992114,1004807,1.848497,1.713513,4.279429
8,District of Columbia,24,19,19,3.39,2.75,2.84,705749,670868,668791,3.400642,2.832152,2.840947
9,Florida,558,412,499,2.60,1.91,2.29,21477737,21589602,21828069,2.598039,1.908326,2.286047
10,Georgia,302,221,228,2.84,2.06,2.11,10617423,10729828,10788029,2.844381,2.059679,2.113454
11,Hawaii,99,92,106,6.99,6.34,7.35,1415872,1451043,1447154,6.992157,6.340267,7.324721
12,Idaho,7,8,4,0.39,0.43,0.21,1787065,1849202,1904314,0.391704,0.432619,0.210049
13,Illinois,326,216,255,2.57,1.69,2.01,12671821,12786580,12686469,2.572637,1.689271,2.010016
14,Indiana,108,92,127,1.60,1.36,1.87,6732219,6788799,6813532,1.604226,1.355173,1.863938
15,Iowa,52,39,49,1.65,1.22,1.53,3155070,3190571,3197689,1.648141,1.222352,1.532357
16,Kansas,37,37,43,1.27,1.26,1.47,2913314,2937919,2937922,1.270031,1.259395,1.46362
17,Kentucky,66,67,57,1.48,1.49,1.26,4467673,4507445,4506589,1.477279,1.48643,1.264815
18,Louisiana,88,99,86,1.89,2.13,1.86,4648794,4651664,4627098,1.892964,2.128271,1.858616
19,Maine,18,17,14,1.34,1.25,1.02,1344212,1363557,1377238,1.339074,1.246739,1.016527
20,Maryland,209,148,192,3.45,2.40,3.11,6045680,6173205,6174610,3.457014,2.397458,3.109508
21,Massachusetts,178,142,151,2.58,2.02,2.16,6892503,6995729,6989690,2.582516,2.02981,2.160325
22,Michigan,131,101,136,1.31,1.00,1.35,9986857,10069577,10037504,1.311724,1.003021,1.354919
23,Minnesota,148,117,134,2.62,2.05,2.35,5639632,5709852,5711471,2.624285,2.04909,2.346156
24,Mississippi,58,41,45,1.95,1.39,1.53,2976149,2958141,2949586,1.948827,1.386006,1.525638
25,Missouri,70,79,77,1.14,1.28,1.25,6137428,6153998,6169823,1.140543,1.283718,1.24801
26,Montana,2,4,3,0.19,0.37,0.27,1068778,1087075,1106227,0.18713,0.36796,0.271192
27,Nebraska,17,33,22,0.88,1.68,1.12,1934408,1962642,1963554,0.878822,1.681407,1.120417
28,Nevada,53,57,61,1.71,1.83,1.94,3080156,3115648,3146402,1.720692,1.829475,1.938722
29,New Hampshire,6,12,12,0.44,0.87,0.86,1359711,1378587,1387505,0.44127,0.870456,0.864862
30,New Jersey,310,245,279,3.49,2.64,3.01,8882190,9271689,9267961,3.49013,2.642453,3.010371
31,New Mexico,41,29,24,1.95,1.37,1.13,2096829,2118390,2116677,1.955334,1.368964,1.133853
32,New York,746,605,681,3.83,3.00,3.43,19453561,20108296,19857492,3.834773,3.008708,3.429436
33,North Carolina,185,159,178,1.76,1.52,1.69,10488084,10449445,10565885,1.763907,1.521612,1.684667
34,North Dakota,18,10,15,2.36,1.28,1.94,762062,779518,777934,2.362013,1.282844,1.928184
35,Ohio,150,130,149,1.28,1.10,1.26,11689100,11797517,11764342,1.283247,1.101927,1.266539
36,Oklahoma,73,67,69,1.84,1.69,1.73,3956971,3964912,3991225,1.844845,1.689823,1.728793
37,Oregon,70,67,78,1.66,1.58,1.84,4217737,4244795,4256301,1.659658,1.578404,1.832577
38,Pennsylvania,199,156,166,1.55,1.20,1.28,12801989,12994440,13012059,1.554446,1.200513,1.27574
39,Rhode Island,14,7,17,1.32,0.64,1.55,1059361,1096345,1096985,1.321551,0.638485,1.549702
40,South Carolina,80,67,88,1.55,1.31,1.70,5148714,5131848,5193266,1.553786,1.305573,1.694502
41,South Dakota,16,16,12,1.80,1.80,1.34,884659,887799,896164,1.808606,1.80221,1.339041
42,Tennessee,129,113,85,1.89,1.63,1.22,6829174,6925619,6968351,1.888955,1.631623,1.219801
43,Texas,1154,883,991,3.98,3.02,3.36,28995881,29232474,29558864,3.979876,3.020613,3.352632
44,Utah,27,29,17,0.84,0.88,0.51,3205958,3283785,3339113,0.842182,0.883127,0.509117
45,Vermont,4,3,2,0.64,0.47,0.31,623989,642893,646972,0.641037,0.466641,0.309132
46,Virginia,191,169,161,2.23,1.96,1.86,8535519,8636471,8657365,2.237708,1.956818,1.859688
47,Washington,221,163,199,2.90,2.11,2.57,7614893,7724031,7740745,2.902208,2.110297,2.570812
48,West Virginia,9,13,7,0.50,0.73,0.39,1792147,1791420,1785526,0.502191,0.725681,0.392041
49,Wisconsin,51,35,66,0.88,0.59,1.12,5822434,5896271,5880101,0.875922,0.593596,1.12243
50,Wyoming,1,0,3,0.17,0.00,0.52,578759,577605,579483,0.172783,0.0,0.517703

### Lecture 6 Data Wrangling and EDA (Part 2) & Text Wrangling and Regex

In [167]:
states = pd.read_csv("../lecture/lec05/data/county_and_state.csv")
populations = pd.read_csv("../lecture/lec05/data/county_and_population.csv")
display(states.head())
display(populations.head())

                       County State
0              De Witt County    IL
1        Lac qui Parle County    MN
2      Lewis and Clark County    MT
3  St John the Baptist Parish    LS

                 County  Population
0                DeWitt       16798
1         Lac Qui Parle        8067
2         Lewis & Clark       55716
3  St. John the Baptist       43044

In [168]:
#不对表格进行规范化，merge会返回无结果
def canonicalize_county(county_series):
    return (county_series
            .str.lower()
            .str.replace(' ', '')
            .str.replace('&', 'and')
            .str.replace('.', '')
            .str.replace('county', '')
            .str.replace('parish', '')
           )

display(canonicalize_county(states["County"]))
display(canonicalize_county(populations["County"]))

0              dewitt
1         lacquiparle
2       lewisandclark
3    stjohnthebaptist
Name: County, dtype: object

0              dewitt
1         lacquiparle
2       lewisandclark
3    stjohnthebaptist
Name: County, dtype: object

In [169]:
log_fname = "../lecture/lec05/data/log.txt"
with open(log_fname, 'r') as f:
    log_lines = f.readlines()
log_lines

['169.237.46.168 - - [26/Jan/2014:10:47:58 -0800] "GET /stat141/Winter04/ HTTP/1.1" 200 2585 "http://anson.ucdavis.edu/courses/"\n',
 '193.205.203.3 - - [2/Feb/2005:17:23:6 -0800] "GET /stat141/Notes/dim.html HTTP/1.0" 404 302 "http://eeyore.ucdavis.edu/stat141/Notes/session.html"\n',
 '169.237.46.240 - "" [3/Feb/2006:10:18:37 -0800] "GET /stat141/homework/Solutions/hw1Sol.pdf HTTP/1.1"\n']

In [170]:
logs = pd.read_csv("../lecture/lec05/data/log.txt",
                   sep='\t',
                   header=None)[0]
logs

0    169.237.46.168 - - [26/Jan/2014:10:47:58 -0800...
1    193.205.203.3 - - [2/Feb/2005:17:23:6 -0800] "...
2    169.237.46.240 - "" [3/Feb/2006:10:18:37 -0800...
Name: 0, dtype: object

In [171]:
#正则表达式
# * 零次或多次
# + 一次或多次
# ？ 零次或一次
# {x, y} 最少x次，最多y次
# [A-Za-z0-9] 范围
# . 表示任意字符
# *? 表示*不再贪婪
# \ 读取下一个字符
# [^] 表示非 not
# ^ 表示开头
# $ 表示结尾
import re
# re.findall(pattern, text) return a list of all matches

In [172]:
# 用()形成捕获组 str.extract str.extractall
pattern_cg = r"([0-9]{3})-([0-9]{2})-([0-9]{4})"
re.findall("123-45-6789", pattern_cg)

[]

In [173]:
# re.sub(pattern, repl, text) 替换成repl
# ser.str.replace(pattern, repl, regex=True)